version: "3.1"
services:
  postgis:
    image: mdillon/postgis:11
    ports:
      - "5432:5432"
    volumes:
      - "./postgis/data:/data"
      - "./postgis/postgis:/var/lib/postgresql"
    environment:
      - POSTGRES_PASSWORD=analytics
      - POSTGRES_USER=analytics
      - POSTGRES_DB=analytics