version: "3.1"
services:
  notebook:
    build:
      context: analysisEnvironment
      dockerfile: notebook.Dockerfile
    container_name: notebook
    volumes:
      - "./analysis:/home/jovyan/work"
      - "./data:/home/jovyan/data"
    ports:
      - "8888:8888"