install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("devtools")
install.packages("arrow")
install.packages("sparklyr")
spark_install(version = "2.4.0")
install.packages("sf")
devtools::inst all_github("harryprince/geospark")
install.packages("mapview")